repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # These hooks merely check -- they don't fix anything
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml
      - id: no-commit-to-branch
        args: [-b, main]
      # These hooks will make changes and fail so you can then verify them and git add them again.
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.7.2
    hooks:
    - id: shellcheck
